name: janusgraph
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py36_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_3
  - pip=19.3.1=py36_0
  - python=3.6.9=h265db76_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.6.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - aenum==2.2.2
    - aiogremlin==3.3.1
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - attrs==19.3.0
    - chardet==3.0.4
    - gremlinpython==3.4.1
    - idna==2.8
    - idna-ssl==1.1.0
    - isodate==0.6.0
    - multidict==4.5.2
    - pyyaml==5.1.2
    - tornado==4.5.3
    - typing-extensions==3.7.4.1
    - yarl==1.3.0

