version: '3'

# As of Titan 1.0.0, only Cassandra 2.1 and Elasticsearch 1.5
# are supported. Attempting to run it on Cassandra 3 results in tears.
#
# Here's the compatibility matrix:
#   http://s3.thinkaurelius.com/docs/titan/1.0.0/version-compat.html

services:
  janus:
    image: janusgraph:1.0.0-hadoop2
    build:
      dockerfile: Dockerfile.janus
      args:
        version: 0.1.1
        hadoop: hadoop2
      context: ./
    ports:
      - "8182:8182"
      - "8184:8184"
    depends_on:
      - db
      - index
  db:
    image: scylladb/scylla:1.7.2
    ports:
     # http://docs.scylladb.com/kb/posix/
     # REST API
     - "10000:10000"
     # CQL ports (native_transport_port)
     - "9042:9042"
     # Thrift (rpc_port)
     - "9160:9160"
     # Internode
     - "7000:7000"
     - "7001:7001"
     # JMX
     - "7199:7199"
     # Prometheus monitoring
     - "9180:9180"
     - "9100:9100"
    volumes:
     - ./data/scylla/data:/var/lib/scylla
  index:
    image: elasticsearch:1.5
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - ./data/elasticsearch/data:/usr/share/elasticsearch/data
